# Generated by Django 5.2.6 on 2025-09-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price_alter_product_stock_and_more'),
        ('products', '0002_view_tracking'),
    ]

    operations = [
    ]
