# Generated by Django 5.2.6 on 2025-09-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20250914_1007'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productview',
            new_name='products_pr_product_e6f684_idx',
            old_name='products_pr_product_7c3be4_idx',
        ),
        migrations.RenameIndex(
            model_name='productview',
            new_name='products_pr_session_5a3656_idx',
            old_name='products_pr_session_25fb20_idx',
        ),
    ]
